### ISSUE TITLE
Error running SQL script: Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by olesa79** [crimdon/SQLToolkitAzure#10]
"Run Sql Script on Azure", version 1.2.4.
I keep getting "Error running SQL script: Cannot bind argument to parameter 'Path' because it is null".
I'm running this on the Hosted VS2017 agent in VSTS.

I have verified that the path I enter in "Specify SQL Script to run" actually exist.

2017-06-06T12:31:18.9616046Z Running Script
2017-06-06T12:31:18.9616046Z 
2017-06-06T12:31:18.9616046Z 
2017-06-06T12:31:19.0306045Z Error running SQL script: Cannot bind argument to parameter 'Path' because it is null.
2017-06-06T12:31:19.0306045Z 
2017-06-06T12:31:19.0306045Z 
2017-06-06T12:31:19.0396061Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
2017-06-06T12:31:19.0396061Z    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-06-06T12:31:19.0396061Z    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-06-06T12:31:19.0396061Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-06-06T12:31:19.0396061Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-06-06T12:31:19.0909617Z ##[error]PowerShell script completed with 1 errors.

**Comment by crimdon** [comment]
Hi there,

Is the path you are passing in a variable or are you entering a path inside the repository?

**Comment by olesa79** [comment]
I've tried both.  Initially I started with the same path that Marcus reported on https://marketplace.visualstudio.com/items?itemName=andrewlackenby.sql-toolkit-azure.

I also just tried adding a Powershell task to run
	$Query = [IO.File]::ReadAllText("d:\a\r1\a\Drop\drop\Web-CopyDatabaseToStaging.sql")
(same absolute path that failed in your task) and that worked fine.

**Comment by olesa79** [comment]
I haven't tried using just a variable - only variable+relative path...

**Comment by crimdon** [comment]
OK I'll have  a look at the code and do some testing in case Microsoft have changed something in VSTS

**Comment by crimdon** [comment]
This is what I get back:

******************************************************************************
Starting: Run Sql Scripts on Test
******************************************************************************
==============================================================================
Task         : Run Sql Script on Azure
Description  : Allows you to run SQL Script in an Azure environment
Version      : 1.2.3
Author       : Andrew Lackenby
Help         : 
==============================================================================
Preparing task execution handler.
Executing the powershell script: d:\a\_tasks\RunSqlScriptAzure_87579a81-e5e6-4993-b2cc-406445da7f28\1.2.3\RunSingleSqlScriptAzure.ps1
Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1
AzurePSCmdletsVersion= 3.5.0
Get-ServiceEndpoint -Name 122c5777-713b-46a9-9800-d7ed03420897 -Context Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.PSHostTaskContext
tenantId= ********
azureSubscriptionName= Pay-As-You-Go
Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
Running Script
This is output from a SQL script
Finished
******************************************************************************
Finishing: Run Sql Scripts on Test
******************************************************************************


I use the following path:

$/Index Manager/Main/test.sql

**Comment by olesa79** [comment]
I do notice the version number is different, 

I tried
$(System.DefaultWorkingDirectory)/Drop/drop/Web-CopyDatabaseToStaging.sql
d:\a\r1\a\Drop\drop\Web-CopyDatabaseToStaging.sql
$/Drop/drop/Web-CopyDatabaseToStaging.sql

I'll just assume that I have some problem on my end (this is my first time using VSTS) and make my own script.

==============================================================================
Task         : Run Sql Script on Azure
Description  : Allows you to run SQL Script in an Azure environment
Version      : 1.2.4
Author       : Andrew Lackenby
Help         : 
==============================================================================
Preparing task execution handler.
Executing the powershell script: d:\a\_tasks\RunSqlScriptAzure_87579a81-e5e6-4993-b2cc-406445da7f28\1.2.4\RunSingleSqlScriptAzure.ps1
Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1
AzurePSCmdletsVersion= 2.1.0
Get-ServiceEndpoint -Name edc567bd-1b30-492f-a961-0e4034bb1514 -Context Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.PSHostTaskContext
tenantId= ********
azureSubscriptionName= Windows Azure MSDN - Visual Studio Ultimate
Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
Running Script
Error running SQL script: Cannot bind argument to parameter 'Path' because it is null.
##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
##[error]PowerShell script completed with 1 errors.

**Comment by crimdon** [comment]
Let me have a look at the versions. I might have an old repo at my end

**Comment by crimdon** [comment]
I've found the bug and fixed it in the latest version. Please update and it should be OK

**Comment by olesa79** [comment]
Works perfectly now!  Thanks
