### ISSUE TITLE
Remove comments flag broken

### ISSUE THREAD

**Issue by dloukola** [crimdon/SQLToolkitAzure#15]
## Run SQL Script**s** on azure
If you un-check the remove comments flag, the task cannot run. It throws error:

` ##[error]System.Management.Automation.MethodInvocationException: Exception calling "ExecuteNonQuery" with "0" argument(s): "ExecuteNonQuery: CommandText property has not been initialized" ---> System.InvalidOperationException: ExecuteNonQuery: CommandText property has not been initialized`

**Comment by crimdon** [comment]
Will have a look at this as soon as I get a chance

**Comment by crimdon** [comment]
Fixed in latest release
