### ISSUE TITLE
Create (or update user)

### ISSUE THREAD

**Issue by henrybeen** [crimdon/SQLToolkitAzure#20]
I'm looking for a task to create (or update password of) an user. I want to pass both username and password in as configuration so I can keep those out of source control and insert them in safely from VSTS.

Would you accept a PR adding such a task?

**Comment by crimdon** [comment]
I'm quite happy to add the new task but won't have time to do my own testing. Will have to rely on yourself for that

**Comment by henrybeen** [comment]
Already done some tests and will add a few more implementations later today. Will let you know outcomes. 

Edit: And thanks!

**Comment by crimdon** [comment]
No problem. New version is now published

**Comment by henrybeen** [comment]
No issues so far on my end. Thanks for your quick responses!
