### ISSUE TITLE
SQLToolkitAzure not compatible with TFS 2017 ( on-premise )

### ISSUE THREAD

**Issue by kjk129** [crimdon/SQLToolkitAzure#25]
I was wondering if there are plans to make SQLToolkitAzure compatible with TFS 2017 ( on-premise )?   

If not, do you know of any alternatives to execute a T-SQL script remotely on an Azure VM from an on-premise TFS deployment?

**Comment by crimdon** [comment]
Hi there,

Its not something I ever had set up for testing. We've just jumped from TFS 2015 to Azure DevOps Server (via TFS 2018) so just starting to get to grips with that.

Can you give me details on what errors you're getting so I can start researching a fix?

**Comment by kjk129** [comment]
The marketplace won’t let me install it saying its wrong version of TFS.   We are running 2017 Update 1 currently and moving to Update 3 soon
Thank you for your response.    Hoping to find a solution !






On Wed, May 29, 2019 at 5:29 AM -0400, "Andrew Lackenby" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

Its not something I ever had set up for testing. We've just jumped from TFS 2015 to Azure DevOps Server (via TFS 2018) so just starting to get to grips with that.

Can you give me details on what errors you're getting so I can start researching a fix?

**Comment by crimdon** [comment]
I've changed the allowed target so it should be available for onsite. Let me know if this works

**Comment by kjk129** [comment]
I’ve installed the Task successfully, however my SQL scripts have parameters and it doesn’t appear that I cannot pass them to the scripts

**Comment by crimdon** [comment]
No sorry the tasks haven't been written to work like that.

**Comment by kjk129** [comment]
Thank you
